### PR TITLE
Added support for Minecraft 1.8.3

### PR DESCRIPTION
**Pull request by AlexMl**
- Added support for v1_8_R2 (1.8.3)
- Fixed NoSuchMethodError on v1_8_R1 (1.8) Craftbukkit. See #4 for details.
- Added messages in startup routine

### CODE REVIEW

**Comment by henry-anderson** [comment]
Did you test this? It doesn't seem to be working for me. The reason I haven't updated it myself is because of an addition in the "PacketStatusListener" class that closes the connection which prevent animations.

**Comment by AlexMl** [comment]
Well I did test it, but not the animations itself. Is there no new way?

**Comment by henry-anderson** [comment]
Not that I have found; however, if I override the 'close' method in the DuplexHandler class, I can check whether the pong has been cancelled, or not and I can stop the connection from closing. This will make the animation work, but the pong packet the signals the end of an animation never gets sent which means that the four green bars the client sees will stay a red x.

**Comment by LarsArtmann** [comment]
Why you don't merge this?

**Pull request merged**
